<?php

namespace Ibrows\SimpleCMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MetaTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaTagRepository extends EntityRepository
{

    public function findAllAlias()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.pathinfo, a.alias');
        $qb->where('a.alias IS NOT null');
        try {
            return $qb->getQuery()->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}